Fix: Preview workflow secret to use

diff --git a/.github/workflows/prod-front.yml b/.github/workflows/prod-front.yml
--- a/.github/workflows/prod-front.yml
+++ b/.github/workflows/prod-front.yml
@@ -1,4 +1,4 @@
-name: Vercel React - Prod
+name: Vercel React - Production
 env:
   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_REACT }}
@@ -23,6 +23,11 @@ jobs:
         run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
       - name: Deploy Project Artifacts to Vercel
         run: echo "DEPLOY_URL=$(vercel deploy --prebuilt --archive=tgz --prod --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_ENV
+      - name: Error Workflow if No Deployment URL
+        if: ${{ env.DEPLOY_URL == '' }}
+        run: |
+          echo "::error::No Deployment URL found, errors must exist while deploying."
+          exit 1
       - name: Send Deployment Notification to Discord
         if: ${{ env.DEPLOY_URL != '' }}
         run: |
